module.exports = {
  apps: [
    {
      name: 'file-watcher',
      script: 'AI_Employee_Vault/file_watcher.py',
      interpreter: 'python',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      error_file: 'AI_Employee_Vault/Logs/pm2-file-watcher-error.log',
      out_file: 'AI_Employee_Vault/Logs/pm2-file-watcher-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'gmail-watcher',
      script: 'AI_Employee_Vault/gmail_watcher.py',
      interpreter: 'python',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      error_file: 'AI_Employee_Vault/Logs/pm2-gmail-watcher-error.log',
      out_file: 'AI_Employee_Vault/Logs/pm2-gmail-watcher-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'whatsapp-watcher',
      script: 'AI_Employee_Vault/whatsapp_watcher.py',
      interpreter: 'python',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      error_file: 'AI_Employee_Vault/Logs/pm2-whatsapp-watcher-error.log',
      out_file: 'AI_Employee_Vault/Logs/pm2-whatsapp-watcher-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'linkedin-automation',
      script: 'AI_Employee_Vault/linkedin_automation.py',
      interpreter: 'python',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      error_file: 'AI_Employee_Vault/Logs/pm2-linkedin-automation-error.log',
      out_file: 'AI_Employee_Vault/Logs/pm2-linkedin-automation-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'orchestrator',
      script: 'AI_Employee_Vault/orchestrator.py',
      interpreter: 'python',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      error_file: 'AI_Employee_Vault/Logs/pm2-orchestrator-error.log',
      out_file: 'AI_Employee_Vault/Logs/pm2-orchestrator-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
