#!/usr/bin/env python3
"""
GMAIL DRAFT GENERATOR - Manual tool for creating email draft replies
No Gmail API or OAuth needed!
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import anthropic
from datetime import datetime

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path("AI_Employee_Vault")
NEEDS_ACTION_FOLDER = VAULT_PATH / "Needs_Action"
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')

print("\n" + "="*60)
print("GMAIL DRAFT GENERATOR")
print("="*60 + "\n")

# Check API key
if not ANTHROPIC_API_KEY or ANTHROPIC_API_KEY == "your_anthropic_api_key_here":
    print("❌ ERROR: API key not configured")
    sys.exit(1)

print(f"✅ API Key loaded: {len(ANTHROPIC_API_KEY)} characters\n")

# Get email details
print("Enter the email subject:")
print("-" * 60)
subject = input("> ")

if not subject.strip():
    print("❌ No subject entered")
    sys.exit(1)

print()
print("Enter the email body/message:")
print("(Paste the email content and press Enter)")
print("-" * 60)
email_body = input("> ")

if not email_body.strip():
    print("❌ No email body entered")
    sys.exit(1)

print()
print("Enter sender name/email:")
sender = input("> ")

if not sender.strip():
    sender = "Customer"

print()
print("="*60)
print("GENERATING AI DRAFT REPLY...")
print("="*60 + "\n")

# Determine priority
text_lower = (subject + " " + email_body).lower()
if any(kw in text_lower for kw in ['urgent', 'asap', 'emergency', 'critical', 'immediate']):
    priority = 'P0 - Critical'
elif any(kw in text_lower for kw in ['invoice', 'payment', 'quote', 'proposal', 'contract', 'deadline']):
    priority = 'P1 - High'
else:
    priority = 'P2 - Medium'

print(f"Priority: {priority}")
print()

# Generate AI draft
try:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    prompt = f"""Draft a professional email reply for a business to send to this customer email.

**Customer Email:**
From: {sender}
Subject: {subject}
Priority: {priority}

Email Body:
{email_body}

**Your Task:**
Write a draft email reply that a business representative could send. This is a DRAFT that will be reviewed by a human before sending.

**Guidelines:**
1. **Tone:** Professional and courteous
2. **Length:** 2-4 paragraphs
3. **Structure:**
   - Greeting
   - Acknowledge their email
   - Address their concern/question
   - Provide helpful information or next steps
   - Professional closing
4. **Urgency Level ({priority}):**
   - P0 (Critical): Express immediate attention
   - P1 (High): Show attentiveness, provide timeline
   - P2 (Medium): Be thorough and helpful
5. **Format:** Proper email format with greeting and signature

**Now write the draft email reply:**"""

    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=600,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    draft_reply = message.content[0].text.strip()

    print("✅ AI DRAFT GENERATED!")
    print()
    print("="*60)
    print("AI DRAFT EMAIL REPLY:")
    print("="*60)
    print(draft_reply)
    print("="*60)
    print()

    # Create file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    safe_sender = "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in sender[:30])
    filename = f"email_{safe_sender}_{timestamp}.md"
    filepath = NEEDS_ACTION_FOLDER / filename

    file_content = f"""# Email: {subject}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority}
**Status:** Pending
**Source:** Manual Entry (Gmail)

---

## Email Details

- **From:** {sender}
- **Subject:** {subject}
- **Received:** {datetime.now().strftime('%H:%M')}
- **Message ID:** `email_{timestamp}`

---

## Email Content

```
{email_body}
```

---

## AI-Generated Draft Reply

**Status:** Ready for Review
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

```
{draft_reply}
```

**IMPORTANT:** This is an AI-generated draft. Please review and modify as needed before sending.

**Approval Required:** {'Yes - Sensitive' if priority in ['P0 - Critical', 'P1 - High'] else 'Review recommended'}

---

## Suggested Actions

- [ ] Review AI draft reply
- [ ] Modify draft if needed
- [ ] Send response via Gmail
- [ ] Mark task as complete

---

**Task File:** `{filename}`
**Generated by:** Gmail Draft Generator
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(file_content)

    print("✅ FILE CREATED!")
    print()
    print(f"Location: {filepath}")
    print()
    print("="*60)
    print("SUCCESS!")
    print("="*60)
    print()
    print("You can now:")
    print("1. Open the file to review the AI draft")
    print("2. Copy the draft reply")
    print("3. Send it via Gmail")
    print()
    print("="*60)

except Exception as e:
    print(f"❌ ERROR: {e}")
    sys.exit(1)
