#!/usr/bin/env python3
"""
LINKEDIN POST GENERATOR - Manual tool for creating LinkedIn posts
No LinkedIn automation or browser needed!
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import anthropic
from datetime import datetime

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path("AI_Employee_Vault")
LINKEDIN_QUEUE = VAULT_PATH / "LinkedIn_Queue"
LINKEDIN_QUEUE.mkdir(exist_ok=True)
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')

print("\n" + "="*60)
print("LINKEDIN POST GENERATOR")
print("="*60 + "\n")

# Check API key
if not ANTHROPIC_API_KEY or ANTHROPIC_API_KEY == "your_anthropic_api_key_here":
    print("❌ ERROR: API key not configured")
    sys.exit(1)

print(f"✅ API Key loaded: {len(ANTHROPIC_API_KEY)} characters\n")

# Get post topic
print("What do you want to post about on LinkedIn?")
print("(Enter the topic or key points)")
print("-" * 60)
topic = input("> ")

if not topic.strip():
    print("❌ No topic entered")
    sys.exit(1)

print()
print("What type of post? (1-4)")
print("1. Professional update/achievement")
print("2. Industry insight/thought leadership")
print("3. Company news/announcement")
print("4. Engagement/question for network")
print("-" * 60)
post_type_choice = input("> ")

post_types = {
    "1": "Professional update/achievement",
    "2": "Industry insight/thought leadership",
    "3": "Company news/announcement",
    "4": "Engagement/question for network"
}

post_type = post_types.get(post_type_choice, "Professional update")

print()
print("="*60)
print("GENERATING LINKEDIN POST...")
print("="*60 + "\n")

# Generate LinkedIn post
try:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    prompt = f"""Create a professional LinkedIn post for a business professional.

**Post Topic:**
{topic}

**Post Type:** {post_type}

**Your Task:**
Write an engaging LinkedIn post that will resonate with a professional audience. This is a DRAFT that will be reviewed before posting.

**Guidelines:**
1. **Length:** 150-300 words (LinkedIn optimal length)
2. **Tone:** Professional but personable
3. **Structure:**
   - Strong opening hook
   - Main content (insight, story, or information)
   - Call to action or question for engagement
4. **Formatting:**
   - Use line breaks for readability
   - 1-2 relevant emojis (professional ones only)
   - Optional: 3-5 relevant hashtags at the end
5. **Engagement:** End with a question or call to action to encourage comments

**Post Type Specific:**
- Professional update: Share achievement with humility, thank team
- Industry insight: Provide value, share expertise
- Company news: Exciting but professional tone
- Engagement: Ask thought-provoking question

**Now write the LinkedIn post:**"""

    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=500,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    draft_post = message.content[0].text.strip()

    print("✅ LINKEDIN POST GENERATED!")
    print()
    print("="*60)
    print("AI-GENERATED LINKEDIN POST:")
    print("="*60)
    print(draft_post)
    print("="*60)
    print()

    # Create file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"linkedin_post_{timestamp}.md"
    filepath = LINKEDIN_QUEUE / filename

    file_content = f"""# LinkedIn Post: {topic[:50]}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Post Type:** {post_type}
**Status:** Draft - Ready for Review
**Source:** Manual Entry

---

## Post Topic

{topic}

---

## AI-Generated LinkedIn Post

**Status:** Ready for Review
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

```
{draft_post}
```

**IMPORTANT:** This is an AI-generated draft. Please review and modify as needed before posting.

---

## Posting Instructions

1. Review the post content
2. Modify if needed (add personal touch, adjust tone)
3. Copy the post
4. Go to LinkedIn
5. Create new post
6. Paste and format
7. Add any images if relevant
8. Post!

---

## Engagement Tips

- Post during business hours (9 AM - 5 PM)
- Best days: Tuesday, Wednesday, Thursday
- Respond to comments within first hour
- Engage with others' posts before posting yours

---

**Task File:** `{filename}`
**Generated by:** LinkedIn Post Generator
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(file_content)

    print("✅ FILE CREATED!")
    print()
    print(f"Location: {filepath}")
    print()
    print("="*60)
    print("SUCCESS!")
    print("="*60)
    print()
    print("You can now:")
    print("1. Open the file to review the post")
    print("2. Copy the post content")
    print("3. Post it on LinkedIn")
    print()
    print("="*60)

except Exception as e:
    print(f"❌ ERROR: {e}")
    sys.exit(1)
