#!/usr/bin/env python3
"""
MANUAL TEST - Create WhatsApp draft without needing WhatsApp Web
Just paste a message and get AI draft instantly
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import anthropic
from datetime import datetime

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path("AI_Employee_Vault")
NEEDS_ACTION_FOLDER = VAULT_PATH / "Needs_Action"
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')

print("\n" + "="*60)
print("MANUAL WHATSAPP DRAFT GENERATOR")
print("="*60 + "\n")

# Check API key
if not ANTHROPIC_API_KEY or ANTHROPIC_API_KEY == "your_anthropic_api_key_here":
    print("❌ ERROR: API key not configured")
    sys.exit(1)

print(f"✅ API Key loaded: {len(ANTHROPIC_API_KEY)} characters\n")

# Get message from user
print("Enter the WhatsApp message you received:")
print("(Type the message and press Enter)")
print("-" * 60)
message_text = input("> ")

if not message_text.strip():
    print("❌ No message entered")
    sys.exit(1)

print()
print("Enter sender name:")
sender_name = input("> ")

if not sender_name.strip():
    sender_name = "Customer"

print()
print("="*60)
print("GENERATING AI DRAFT...")
print("="*60 + "\n")

# Determine priority
text_lower = message_text.lower()
if any(kw in text_lower for kw in ['urgent', 'asap', 'emergency', 'critical', 'help', 'problem']):
    priority = 'P0 - Critical'
elif any(kw in text_lower for kw in ['pricing', 'quote', 'order', 'payment', 'invoice', 'delivery']):
    priority = 'P1 - High'
else:
    priority = 'P2 - Medium'

print(f"Priority: {priority}")
print()

# Generate AI draft
try:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    prompt = f"""Draft a professional WhatsApp reply for a business to send to this customer message.

**Customer Message:**
From: {sender_name}
Priority: {priority}
Message: {message_text}

**Your Task:**
Write a draft WhatsApp reply that a business representative could send. This is a DRAFT that will be reviewed by a human before sending.

**Guidelines:**
1. **Tone:** Professional, warm, and conversational (WhatsApp style)
2. **Length:** 2-4 short paragraphs maximum
3. **Emojis:** Use 1-2 appropriate emojis for friendliness
4. **Content:**
   - Acknowledge their message
   - Address their specific concern or question
   - Provide helpful information or next steps
   - Ask clarifying questions if needed
5. **Urgency Level ({priority}):**
   - P0 (Critical): Express immediate attention, offer quick resolution
   - P1 (High): Show attentiveness, provide clear timeline
   - P2 (Medium): Be thorough and helpful
6. **Closing:** End with a clear question or call to action

**Now write the draft reply:**"""

    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=500,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    draft_reply = message.content[0].text.strip()

    print("✅ AI DRAFT GENERATED!")
    print()
    print("="*60)
    print("AI DRAFT REPLY:")
    print("="*60)
    print(draft_reply)
    print("="*60)
    print()

    # Create file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    safe_sender = "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in sender_name[:30])
    filename = f"whatsapp_{safe_sender}_{timestamp}.md"
    filepath = NEEDS_ACTION_FOLDER / filename

    file_content = f"""# WhatsApp Message: {sender_name}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority}
**Status:** Pending
**Source:** Manual Entry

---

## Message Details

- **From:** {sender_name}
- **Received:** {datetime.now().strftime('%H:%M')}
- **Message ID:** `manual_{timestamp}`
- **Chat Type:** Individual

---

## Message Content

```
{message_text}
```

---

## AI-Generated Draft Reply

**Status:** Ready for Review
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

```
{draft_reply}
```

**IMPORTANT:** This is an AI-generated draft. Please review and modify as needed before sending.

**Approval Required:** {'Yes - New contact or sensitive' if priority in ['P0 - Critical', 'P1 - High'] else 'Review recommended'}

---

## Suggested Actions

- [ ] Review AI draft reply
- [ ] Modify draft if needed
- [ ] Send response via WhatsApp
- [ ] Mark task as complete

---

**Task File:** `{filename}`
**Generated by:** Manual Draft Generator
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(file_content)

    print("✅ FILE CREATED!")
    print()
    print(f"Location: {filepath}")
    print()
    print("="*60)
    print("SUCCESS!")
    print("="*60)
    print()
    print("You can now:")
    print("1. Open the file to review the AI draft")
    print("2. Copy the draft reply")
    print("3. Send it via WhatsApp")
    print()
    print("="*60)

except Exception as e:
    print(f"❌ ERROR: {e}")
    sys.exit(1)
