#!/usr/bin/env python3
"""
Simple test - Creates a WhatsApp message file with AI draft
WITHOUT needing WhatsApp Web login
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import anthropic
from datetime import datetime

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path("AI_Employee_Vault")
NEEDS_ACTION_FOLDER = VAULT_PATH / "Needs_Action"
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')

print("\n" + "="*60)
print("SIMPLE TEST - AI Draft Generation")
print("="*60 + "\n")

# Check API key
if not ANTHROPIC_API_KEY or ANTHROPIC_API_KEY == "your_anthropic_api_key_here":
    print("❌ ERROR: API key not configured")
    print("Edit .env file and add your API key")
    sys.exit(1)

print(f"✅ API Key loaded: {len(ANTHROPIC_API_KEY)} characters")
print(f"   Starts with: {ANTHROPIC_API_KEY[:15]}...")
print()

# Test message
test_message = {
    'sender': 'Test Customer',
    'text': 'urgent need help with pricing for 50 units',
    'time': datetime.now().strftime('%H:%M'),
    'priority': 'P0 - Critical'
}

print("="*60)
print("TEST MESSAGE:")
print("="*60)
print(f"From: {test_message['sender']}")
print(f"Message: {test_message['text']}")
print(f"Priority: {test_message['priority']}")
print()

# Generate AI draft
print("🤖 Generating AI draft reply...")
print()

try:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    prompt = f"""Draft a professional WhatsApp reply for a business to send to this customer message.

**Customer Message:**
From: {test_message['sender']}
Priority: {test_message['priority']}
Message: {test_message['text']}

**Your Task:**
Write a draft WhatsApp reply that a business representative could send. This is a DRAFT that will be reviewed by a human before sending.

**Guidelines:**
1. **Tone:** Professional, warm, and conversational (WhatsApp style)
2. **Length:** 2-4 short paragraphs maximum
3. **Emojis:** Use 1-2 appropriate emojis for friendliness
4. **Content:**
   - Acknowledge their message
   - Address their specific concern or question
   - Provide helpful information or next steps
   - Ask clarifying questions if needed
5. **Urgency Level ({test_message['priority']}):**
   - P0 (Critical): Express immediate attention, offer quick resolution
6. **Closing:** End with a clear question or call to action

**Now write the draft reply:**"""

    message = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=500,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    draft_reply = message.content[0].text.strip()

    print("✅ AI Draft Generated!")
    print()
    print("="*60)
    print("AI DRAFT REPLY:")
    print("="*60)
    print(draft_reply)
    print("="*60)
    print()

    # Create file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"whatsapp_Test_Customer_{timestamp}.md"
    filepath = NEEDS_ACTION_FOLDER / filename

    file_content = f"""# WhatsApp Message: {test_message['sender']}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {test_message['priority']}
**Status:** Pending
**Source:** Simple Test Script

---

## Message Details

- **From:** {test_message['sender']}
- **Received:** {test_message['time']}
- **Message ID:** `test_{timestamp}`
- **Chat Type:** Individual

---

## Message Content

```
{test_message['text']}
```

---

## AI-Generated Draft Reply

**Status:** Ready for Review
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

```
{draft_reply}
```

**IMPORTANT:** This is an AI-generated draft. Please review and modify as needed before sending.

**Approval Required:** Yes - New contact or sensitive

---

## Suggested Actions

- [ ] Read and analyze message
- [ ] Review AI draft reply
- [ ] Modify draft if needed
- [ ] Send response via WhatsApp
- [ ] Mark task as complete

---

**Task File:** `{filename}`
**Generated by:** Simple Test Script
"""

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(file_content)

    print("✅ FILE CREATED!")
    print()
    print(f"Location: {filepath}")
    print()
    print("="*60)
    print("SUCCESS!")
    print("="*60)
    print()
    print("Open this file to see the AI draft:")
    print(f"   {filepath}")
    print()
    print("This proves your API key is working and AI drafts")
    print("are being generated correctly!")
    print()
    print("="*60)

except Exception as e:
    print(f"❌ ERROR: {e}")
    sys.exit(1)
