#!/usr/bin/env python3
"""
Manual WhatsApp Message Test
Simulates a message to test the system
"""

import os
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import anthropic

# Load environment
load_dotenv()
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')

# Paths
VAULT_PATH = Path(__file__).parent / "AI_Employee_Vault"
NEEDS_ACTION_FOLDER = VAULT_PATH / "Needs_Action"
NEEDS_ACTION_FOLDER.mkdir(exist_ok=True)

# Keywords
URGENT_KEYWORDS = ['urgent', 'asap', 'emergency', 'critical', 'help', 'problem']
BUSINESS_KEYWORDS = ['pricing', 'quote', 'order', 'payment', 'invoice', 'delivery']
INQUIRY_KEYWORDS = ['question', 'inquiry', 'information', 'details', 'available']

def determine_priority(message_text):
    """Determine message priority"""
    text = message_text.lower()

    # Check for urgent keywords
    urgent_matches = [kw for kw in URGENT_KEYWORDS if kw in text]
    if urgent_matches:
        return 'P0 - Critical', urgent_matches

    # Check for business keywords
    business_matches = [kw for kw in BUSINESS_KEYWORDS if kw in text]
    if business_matches:
        return 'P1 - High', business_matches

    # Check for inquiry keywords
    inquiry_matches = [kw for kw in INQUIRY_KEYWORDS if kw in text]
    if inquiry_matches:
        return 'P2 - Medium', inquiry_matches

    return 'P2 - Medium', []

def generate_draft_reply(message_text, sender, priority):
    """Generate AI draft reply"""
    try:
        if not ANTHROPIC_API_KEY:
            print("[ERROR] API Key not set")
            return None

        client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

        prompt = f"""Draft a professional WhatsApp reply for this customer message.

**Customer Message:**
From: {sender}
Priority: {priority}
Message: {message_text}

**Your Task:**
Write a draft WhatsApp reply that a business representative could send.

**Guidelines:**
1. Tone: Professional, warm, conversational
2. Length: 2-4 short paragraphs
3. Emojis: Use 1-2 appropriate emojis
4. Acknowledge their message and address their concern
5. End with a clear question or call to action

Write the draft reply:"""

        print("[AI] Calling Claude API...")
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=500,
            messages=[{"role": "user", "content": prompt}]
        )

        draft = message.content[0].text.strip()
        print("[OK] AI draft generated!")
        return draft

    except Exception as e:
        print(f"[ERROR] Error generating draft: {e}")
        return None

def create_task_file(sender, message_text):
    """Create task file"""
    print("\n" + "="*70)
    print("CREATING TASK FILE")
    print("="*70)

    # Determine priority
    priority, keywords = determine_priority(message_text)
    print(f"Priority: {priority}")
    print(f"Keywords matched: {', '.join(keywords) if keywords else 'None'}")

    # Generate AI draft
    draft_reply = generate_draft_reply(message_text, sender, priority)

    # Create filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    safe_sender = "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in sender[:30])
    filename = f"whatsapp_{safe_sender}_{timestamp}.md"
    filepath = NEEDS_ACTION_FOLDER / filename

    # Build AI draft section
    if draft_reply:
        ai_section = f"""## AI-Generated Draft Reply

**Status:** Ready for Review
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

```
{draft_reply}
```

**IMPORTANT:** This is an AI-generated draft. Please review before sending.

---

"""
    else:
        ai_section = """## AI-Generated Draft Reply

**Status:** Not Available
**Reason:** API key not configured or generation failed

---

"""

    # Create content
    content = f"""# WhatsApp Message: {sender}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Priority:** {priority}
**Status:** Pending
**Source:** Manual Test

---

## Message Details

- **From:** {sender}
- **Received:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Keywords Matched:** {', '.join(keywords) if keywords else 'None'}

---

## Message Content

```
{message_text}
```

---

{ai_section}

## Suggested Actions

- [ ] Read and analyze message
- [ ] Draft reply
- [ ] Send response via WhatsApp
- [ ] Update Dashboard

---

**Task File:** `{filename}`
**Generated by:** Manual Test Script
"""

    # Write file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\n[OK] File created: {filename}")
    print(f"[OK] Location: {filepath}")
    print("="*70)

    return filepath

def main():
    """Main test function"""
    print("="*70)
    print("WhatsApp Manual Test")
    print("="*70)
    print()

    # Check API key
    if ANTHROPIC_API_KEY:
        print(f"[OK] API Key loaded (length: {len(ANTHROPIC_API_KEY)})")
    else:
        print("[ERROR] API Key NOT loaded")

    print()

    # Test message
    sender = input("Enter sender name (e.g., Sister Name): ").strip()
    if not sender:
        sender = "Test Sister"

    print()
    message = input("Enter message text: ").strip()
    if not message:
        message = "urgent help needed with pricing and payment"

    print()
    print("Processing message...")

    # Create task
    filepath = create_task_file(sender, message)

    print()
    print("[OK] TEST COMPLETE!")
    print()
    print("Next steps:")
    print(f"1. Check file: {filepath}")
    print("2. Verify AI draft was generated")
    print("3. If this works, the watcher should work too")
    print()

if __name__ == "__main__":
    main()
