#!/usr/bin/env python3
"""
Morning Briefing Generator
Creates a comprehensive morning briefing with pending tasks and priorities
"""

import os
from datetime import datetime, timedelta
from pathlib import Path

# Configuration
VAULT_PATH = Path(__file__).parent
NEEDS_ACTION = VAULT_PATH / "Needs_Action"
PENDING_APPROVAL = VAULT_PATH / "Pending_Approval"
LOGS_FOLDER = VAULT_PATH / "Logs"
DASHBOARD = VAULT_PATH / "Dashboard.md"


def generate_briefing():
    """Generate morning briefing"""

    # Count tasks
    needs_action_files = list(NEEDS_ACTION.glob("*.md"))
    pending_approval_files = list(PENDING_APPROVAL.glob("*.md"))

    # Categorize by priority
    critical = []
    high = []
    medium = []
    low = []

    for file_path in needs_action_files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                if 'P0 - Critical' in content:
                    critical.append(file_path.name)
                elif 'P1 - High' in content:
                    high.append(file_path.name)
                elif 'P2 - Medium' in content:
                    medium.append(file_path.name)
                else:
                    low.append(file_path.name)
        except:
            continue

    # Generate briefing
    briefing = f"""# Morning Briefing - {datetime.now().strftime('%A, %B %d, %Y')}

**Generated:** {datetime.now().strftime('%H:%M:%S')}

---

## 🌅 Good Morning!

Here's your briefing for today:

---

## 📊 Overview

- **Total Tasks:** {len(needs_action_files)}
- **Pending Approvals:** {len(pending_approval_files)}
- **Critical (P0):** {len(critical)}
- **High (P1):** {len(high)}
- **Medium (P2):** {len(medium)}
- **Low (P3):** {len(low)}

---

## 🚨 Critical Tasks (P0)

"""

    if critical:
        for task in critical:
            briefing += f"- {task}\n"
    else:
        briefing += "✅ No critical tasks\n"

    briefing += "\n---\n\n## ⚡ High Priority Tasks (P1)\n\n"

    if high:
        for task in high[:5]:  # Top 5
            briefing += f"- {task}\n"
        if len(high) > 5:
            briefing += f"\n*...and {len(high) - 5} more*\n"
    else:
        briefing += "✅ No high priority tasks\n"

    briefing += f"\n---\n\n## ⏳ Pending Approvals\n\n"

    if pending_approval_files:
        for approval in pending_approval_files[:5]:
            briefing += f"- {approval.name}\n"
        if len(pending_approval_files) > 5:
            briefing += f"\n*...and {len(pending_approval_files) - 5} more*\n"
    else:
        briefing += "✅ No pending approvals\n"

    briefing += f"""

---

## 🎯 Today's Focus

1. Clear all P0 (Critical) tasks
2. Review and approve/reject pending items
3. Address top 3 P1 (High) tasks
4. Prepare LinkedIn content for the week

---

## 📅 Scheduled Activities

- **8:00 AM** - Morning briefing (this)
- **12:00 PM** - Approval check
- **6:00 PM** - End-of-day summary
- **11:00 PM** - LinkedIn content prep

---

**Have a productive day!** 🚀

---

*Generated by: Morning Briefing Generator*
"""

    # Save briefing
    briefing_file = LOGS_FOLDER / f"morning_briefing_{datetime.now().strftime('%Y%m%d')}.md"
    with open(briefing_file, 'w', encoding='utf-8') as f:
        f.write(briefing)

    print(f"Morning briefing generated: {briefing_file}")
    print("\n" + briefing)


if __name__ == "__main__":
    generate_briefing()
