#!/usr/bin/env python3
"""
End-of-Day Summary Generator
Creates a comprehensive summary of the day's activities
"""

import os
from datetime import datetime
from pathlib import Path

# Configuration
VAULT_PATH = Path(__file__).parent
DONE = VAULT_PATH / "Done"
LOGS_FOLDER = VAULT_PATH / "Logs"
LINKEDIN_POSTED = VAULT_PATH / "LinkedIn_Posted"
REJECTED = VAULT_PATH / "Rejected"


def generate_summary():
    """Generate end-of-day summary"""

    today = datetime.now().strftime('%Y%m%d')

    # Count today's activities
    done_today = [f for f in DONE.glob("*.md") if today in f.name]
    posted_today = [f for f in LINKEDIN_POSTED.glob("*.md") if today in f.name]
    rejected_today = [f for f in REJECTED.glob("*.md") if today in f.name]

    # Read today's logs
    log_files = list(LOGS_FOLDER.glob(f"*{today}*.md"))

    # Generate summary
    summary = f"""# End-of-Day Summary - {datetime.now().strftime('%A, %B %d, %Y')}

**Generated:** {datetime.now().strftime('%H:%M:%S')}

---

## 📊 Today's Achievements

### Tasks Completed
- **Total Completed:** {len(done_today)}

"""

    if done_today:
        for task in done_today[:10]:  # Top 10
            summary += f"- ✅ {task.name}\n"
        if len(done_today) > 10:
            summary += f"\n*...and {len(done_today) - 10} more*\n"
    else:
        summary += "No tasks completed today\n"

    summary += f"""

### LinkedIn Activity
- **Posts Published:** {len(posted_today)}

"""

    if posted_today:
        for post in posted_today:
            summary += f"- 📱 {post.name}\n"

    summary += f"""

### Approvals
- **Rejected/Expired:** {len(rejected_today)}

---

## 📈 Performance Metrics

### Response Times
- Average task completion: [To be calculated]
- Approval turnaround: [To be calculated]

### Quality Metrics
- Tasks completed on time: [To be calculated]
- Client satisfaction: [To be calculated]

---

## 🎯 Tomorrow's Priorities

Based on today's activities, focus on:

1. Follow up on pending items
2. Address any urgent issues
3. Continue LinkedIn engagement
4. Review and optimize workflows

---

## 📝 Notes & Observations

"""

    # Add any notable events from logs
    summary += "*Review logs for detailed activity*\n\n"

    summary += f"""---

## 🌙 End of Day Checklist

- [ ] All critical tasks addressed
- [ ] Pending approvals reviewed
- [ ] Tomorrow's priorities identified
- [ ] Systems running smoothly
- [ ] Logs reviewed

---

**Great work today!** Rest well and see you tomorrow. 🌟

---

*Generated by: End-of-Day Summary Generator*
"""

    # Save summary
    summary_file = LOGS_FOLDER / f"eod_summary_{datetime.now().strftime('%Y%m%d')}.md"
    with open(summary_file, 'w', encoding='utf-8') as f:
        f.write(summary)

    print(f"End-of-day summary generated: {summary_file}")
    print("\n" + summary)


if __name__ == "__main__":
    generate_summary()
