#!/usr/bin/env python3
"""
LinkedIn Content Preparation
Generates LinkedIn post ideas and queues them for approval
"""

import os
from datetime import datetime, timedelta
from pathlib import Path

# Configuration
VAULT_PATH = Path(__file__).parent
LINKEDIN_IDEAS = VAULT_PATH / "LinkedIn_Ideas"
LINKEDIN_QUEUE = VAULT_PATH / "LinkedIn_Queue"
PENDING_APPROVAL = VAULT_PATH / "Pending_Approval"
BUSINESS_GOALS = VAULT_PATH / "Business_Goals.md"

LINKEDIN_IDEAS.mkdir(exist_ok=True)
LINKEDIN_QUEUE.mkdir(exist_ok=True)


def get_next_weekday():
    """Get next business day"""
    tomorrow = datetime.now() + timedelta(days=1)
    # Skip weekends
    while tomorrow.weekday() >= 5:  # 5=Saturday, 6=Sunday
        tomorrow += timedelta(days=1)
    return tomorrow


def generate_post_ideas():
    """Generate LinkedIn post ideas for the week"""

    next_day = get_next_weekday()
    weekday = next_day.strftime('%A')

    # Post themes by day
    themes = {
        'Monday': 'Industry Insights',
        'Tuesday': 'Tips & Best Practices',
        'Wednesday': 'Case Study',
        'Thursday': 'Problem-Solving',
        'Friday': 'Weekly Recap'
    }

    theme = themes.get(weekday, 'General')

    # Generate post ideas
    ideas = f"""# LinkedIn Post Ideas - {next_day.strftime('%A, %B %d, %Y')}

**Theme:** {theme}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## 💡 Post Ideas for {weekday}

### Idea 1: {theme} Post

**Hook:**
[Attention-grabbing first line]

**Body:**
[Main content - 3-5 short paragraphs]

**CTA:**
[Call to action]

**Hashtags:**
#Business #Growth #Innovation

---

### Idea 2: Alternative Approach

**Hook:**
[Different angle on the same theme]

**Body:**
[Alternative content]

**CTA:**
[Different call to action]

**Hashtags:**
#Leadership #Strategy #Success

---

### Idea 3: Personal Story

**Hook:**
[Personal experience or lesson]

**Body:**
[Story with takeaway]

**CTA:**
[Engagement question]

**Hashtags:**
#Entrepreneurship #Lessons #Journey

---

## 📝 Notes

- Review Business_Goals.md for alignment
- Check recent post performance
- Consider current trends
- Personalize based on recent experiences

---

## ✅ Next Steps

1. Choose one idea
2. Refine and personalize
3. Create approval request
4. Schedule for optimal time (8 AM, 12 PM, or 5 PM)

---

*Generated by: LinkedIn Content Preparation*
"""

    # Save ideas
    ideas_file = LINKEDIN_IDEAS / f"ideas_{next_day.strftime('%Y%m%d')}.md"
    with open(ideas_file, 'w', encoding='utf-8') as f:
        f.write(ideas)

    print(f"LinkedIn ideas generated: {ideas_file}")

    # Create a sample approval request
    create_sample_approval(next_day, theme)


def create_sample_approval(post_date, theme):
    """Create a sample approval request for tomorrow's post"""

    sample_post = f"""🚀 {theme} for {post_date.strftime('%A')}

[This is a template - customize with actual content]

Here's what I've learned about [topic]:

→ [Key point 1]
→ [Key point 2]
→ [Key point 3]

The biggest takeaway? [Main insight]

What's your experience with this? Let me know in the comments!

#Business #Growth #Innovation"""

    expiry_time = (datetime.now() + timedelta(hours=12)).strftime('%Y-%m-%d %H:%M:%S')

    approval_content = f"""# LinkedIn Post Approval Request

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Expires:** {expiry_time}
**Type:** LinkedIn Post
**Category:** {theme}
**Status:** PENDING
**Scheduled For:** {post_date.strftime('%Y-%m-%d')} at 8:00 AM

---

## 📝 Post Content

```
{sample_post}
```

---

## 🎯 Post Details

- **Theme:** {theme}
- **Target Audience:** Business professionals, entrepreneurs
- **Estimated Reach:** 500-1000 connections
- **Best Time to Post:** 8:00 AM (commute time)
- **Expected Engagement:** 50+ likes, 10+ comments

---

## 📊 Strategy Alignment

This post aligns with our content strategy:
- Provides value to audience
- Demonstrates expertise
- Encourages engagement
- Builds brand awareness

---

## ✅ APPROVAL INSTRUCTIONS

### To APPROVE:
1. Review and customize the content above
2. Move this file to `/Approved` folder
3. Post will be published at scheduled time

### To REJECT:
1. Move this file to `/Rejected` folder
2. Add rejection reason in Notes section below

### To MODIFY:
1. Edit the post content above
2. Move to `/Approved` folder when ready

---

## 📝 Notes

*Add any notes or modifications here*

---

## ⏰ Expiry Information

**Expires:** {expiry_time}

After expiry, this request will be automatically rejected.

---

**Approval File:** `linkedin_post_approval_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md`
**Generated by:** LinkedIn Content Preparation
"""

    # Save approval request
    approval_file = PENDING_APPROVAL / f"linkedin_post_approval_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    with open(approval_file, 'w', encoding='utf-8') as f:
        f.write(approval_content)

    print(f"Sample approval request created: {approval_file}")


if __name__ == "__main__":
    generate_post_ideas()
